server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taotao?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  mvc:
    servlet:
      path: /search/

  data:
    solr:
      host: http://localhost:8983/solr/new_core
      # 这个是自定义属性，用于批量导入数据到solr中
      batch_size: 500

mybatis:
  type-aliases-package: com.taotao.pojo
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    # 开启mybatis数据库字段自动映射成小驼峰

    map-underscore-to-camel-case: true



logging:
  level:
    root: info
    com.taotao.mapper: debug
